### ISSUE TITLE
Hitbox for main menu on mobile is too small.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/AleyDafna-Shop#10]
![screenshot from 2016-04-27 11-21-59](https://cloud.githubusercontent.com/assets/1911594/14846060/766d8d4e-0c6a-11e6-994a-59600ddcaba6.png)
As you can see, you have to perfectly tap on middle line in order menu to show. We need this area to be much bigger.

**Comment by talrez11** [comment]
Fixed issue
