### ISSUE TITLE
SVG images are not visible on inner pages.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/AleyDafna-Shop#12]
SVG sprites are not being displayed on inner pages. This is most likely due to relative `xlink:href` paths.

Current code looks like this:

``` xml
<svg>
    <use
        href="#basket"
        xlink:href="site/images/site-sprite.svg#basket"
        />
</svg>
```

Instead of relative paths `xlink:href` should be `_BASEURL.'site/images/site-sprite.svg#basked'`. This will cause this attribute to point to absolute paths with full domain included and should fix the issue.

**Comment by talrez11** [comment]
Fixed SVG files to point to absolute pathes
