### ISSUE TITLE
Pages in checkout process are not centered

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#15]
![image](https://cloud.githubusercontent.com/assets/18681483/14863244/8ded94f2-0cbd-11e6-8584-bfc7b4a6e000.png)

**Comment by MeanEYE** [comment]
This is most likely due to arrows being positioned outside of container and iPhone tries to show it. Either way arrows need to be fixed and then retest if this issue is still showing.
