### ISSUE TITLE
Tranzila is not showing the iframe  right

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#17]
![image](https://cloud.githubusercontent.com/assets/18681483/14863285/c0bb60a8-0cbd-11e6-8980-f2ca47aa1ce3.png)

**Comment by MeanEYE** [comment]
Patch submitted. Waiting for confirmation before making an official change to Caracal.

**Comment by MeanEYE** [comment]
Change has effect but it's still unusable. Waiting for further info from @hanan-avzuk.
![screenshot from 2016-05-01 12-40-10](https://cloud.githubusercontent.com/assets/1911594/14941131/dd844450-0f99-11e6-9d39-4f4a7be053d9.png)

**Comment by MeanEYE** [comment]
Temporarily accepted solution until we find a better one without customizing another Tranzila checkout file.
