### ISSUE TITLE
Add GTM dataLayer leadSent Event

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/AleyDafna-Shop#26]
Push dataLayer event for each form submission.

**Comment by MeanEYE** [comment]
Can you give sample data to be added?

**Comment by eyalway2cu** [comment]
dataLayer.push({"event": "leadSent"});

**Comment by MeanEYE** [comment]
No extra information needed?

**Comment by eyalway2cu** [comment]
nothing additional needed, this only lets me know that a form has been submitted. Since forms are on different URL's by what I can see I will know which form it was according to URL.
