### ISSUE TITLE
Tranzilla is wasting time and money

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/AleyDafna-Shop#48]
Talk to them abuot how we can make this stop or we use a different company.

**Comment by MeanEYE** [comment]
Welp, I assume this is suppose to be assigned to @hanan-avzuk. As far as am concerned, fix is committed and waiting for further testing. However, issue should have been filed on Caracal repo.

**Comment by MeanEYE** [comment]
@eyalway2cu can you update me on this? They are working for a while with Tranzila. So I guess this issue is no longer valid?
