### ISSUE TITLE
Format all prices the same way.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/AleyDafna-Shop#5]
Ideally prices should have 2 decimal places. Default system price is formated this way but prices based on property are not. Instead of using `<cms:var param="value"/>` we need to use `<cms:var name="number_format($params['value'])"/>`.

**Comment by MeanEYE** [comment]
Also, currency needs to be included but as a `data-currency` with corresponding CSS `content: attr(data-currency)`.

**Comment by talrez11** [comment]
Done
