### ISSUE TITLE
Delivery area articles

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#51]
At the footer add title of group of articles called "Delivery Areas" and under it a list of article titles, each title will lead to article for each city. this is for SEO purposes. 
![screenshot from 2016-10-26 13-53-42](https://cloud.githubusercontent.com/assets/18681483/19723388/c7bb9652-9b83-11e6-8123-c0a5ab23ca28.png)

**Comment by MeanEYE** [comment]
You mean at the part with dark green background?

**Comment by hanan-avzuk** [comment]
Yes
Under or instead of  מבצעים

**Comment by MeanEYE** [comment]
@hanan-avzuk was this done?

**Comment by hanan-avzuk** [comment]
This wasnt done, I want to charge client for that

**Comment by MeanEYE** [comment]
So wait for confirmation or do it?

**Comment by iliyaM** [comment]
![screenshot from 2016-12-15 13-28-02](https://cloud.githubusercontent.com/assets/20294485/21222395/552f1758-c2ca-11e6-813a-9287049f65bd.png)

i need content and further instructions what needs to show in "delivery" page

**Comment by MeanEYE** [comment]
@iliyaM content is something guys from Top Interactive will do. Content of this menu should be from article group. And we need additional URL pattern to handle showing it. Also, page showing this article will include shop category of the same `text_id`. For example if they make article with `text_id` = _'ramat-gan'_ system would generate URL `/areas/ramat-gan` and show shop category with same name.

**Comment by talrez11** [comment]
Am closing the issue becasue iliya has made those changes and waiting for you to deploy
