### ISSUE TITLE
Search lead to blank page

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#52]
When searching for nothing or searching for: "'" or searching for "," lead to this: [](http://bsexy.co.il/search?query=%27
)

**Comment by hanan-avzuk** [comment]
http://bsexy.co.il/search?query=%27

**Comment by MeanEYE** [comment]
This issue will be fixed along with Bsexy.

**Comment by MeanEYE** [comment]
This was erroneously reported here. So by mistake this site got search mechanism as well. Issue was originally meant for Bsexy site.
