### ISSUE TITLE
Agree to terms checkbox doesn't work on checkout page.

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#55]
When I try to checkout, I cant agree to terms of use... cant mark the checkbox...maybe there is more shit there, but I cant move forward

**Comment by MeanEYE** [comment]
It does work but CSS but check mark is not visible. Recent updates to CSS compiler broke paths which lead to images in modules directory.

**Comment by hanan-avzuk** [comment]
fix then

**Comment by MeanEYE** [comment]
Am leaving the note for people who might run into issue or to my future self. No need to give instructions.
