### ISSUE TITLE
Fixes to russian language file.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/AleyDafna-Shop#72]
I've emailed them to you.

**Comment by iliyaM** [comment]
I was told to wait. dont remember why.

**Comment by MeanEYE** [comment]
By who?

**Comment by iliyaM** [comment]
You.
There was something with language files.

בתאריך 10 במאי 2017 01:36 PM,‏ "Mladen Mijatov" <notifications@github.com>
כתב:

**Comment by MeanEYE** [comment]
I think that was until I pushed. You can pull and do them.

**Comment by iliyaM** [comment]
The constants that appear in checkout process dont use the russian ones. 
there are russian translated constant and it still uses hebrew.

**Comment by MeanEYE** [comment]
That's Caracal translation.

**Comment by iliyaM** [comment]
What with this issue?
