### ISSUE TITLE
analytics E commerce data is not being passed since February

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/AleyDafna-Shop#75]
Just got word from the client today that since February no transactions have been reported even though there have been transactions on the site.

**Comment by MeanEYE** [comment]
We are scheduled to upgrade their site. I won't debug this until that happens just in case issue is already resolved.

**Comment by hanan-avzuk** [comment]
When wold this be solved? we need a dead line

**Comment by MeanEYE** [comment]
Site was synchronized days ago. Needs testing.

**Comment by hanan-avzuk** [comment]
Can you check if you fire measurement protocol? cause this is what we are looking to find out

**Comment by MeanEYE** [comment]
Considering it was never implemented, I am pretty sure I don't fire measurement protocol.

**Comment by eyalway2cu** [comment]
You are right, it looks like the transaction was picked up from the dataLayer. Are you still sending data via dataLayer for each successful purchase on the thank you page?

**Comment by MeanEYE** [comment]
Code from [checkout.js](https://github.com/Way2CU/AleyDafna-Shop/blob/master/site/scripts/checkout.js#L309-L323) is called [here](https://github.com/Way2CU/AleyDafna-Shop/blob/master/site/scripts/main.js#L1251-L1252).

The only reason why this would not submit is if either `dataLayer` is missing or specific message container is missing. If site is not submitting I would assume former.
