### ISSUE TITLE
Hide 1700 phone number

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/AleyDafna-Shop#8]
Hide the 1-700 number from all locations, do not remove for future use.

**Comment by talrez11** [comment]
Removed from Mobile menu

**Comment by MeanEYE** [comment]
If the issue was to **remove** phone number, then @eyalway2cu would have written that as description. You failed to read both title and description which _explicitly states_ **NOT TO REMOVE**.

**Comment by talrez11** [comment]
Commented out all 1700 phone number both desktop and mobile versions

**Comment by MeanEYE** [comment]
Mark it as closed then.
